apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook-stack
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: namespace
            wave: "-1"
          - name: redis
            wave: "0"
          - name: guestbook
            wave: "1"
  template:
    metadata:
      name: "{{name}}"
      annotations:
        argocd.argoproj.io/sync-wave: "{{wave}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/alexz-ops/argocd.git
        targetRevision: HEAD
        path: "guestbook-k8s/{{name}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: guestbook
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
            - CreateNamespace=true