apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: guestbook-infra
            appGroup: guestbook
            component: infra
            wave: "-1"
          - name: guestbook-app
            appGroup: guestbook
            component: app
            wave: "0"
  template:
    metadata:
      name: "{{name}}"
      annotations:
        argocd.argoproj.io/sync-wave: "{{wave}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/alexz-ops/argocd.git
        targetRevision: HEAD
        path: "{{appGroup}}-k8s/{{component}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{appGroup}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
