{{- $ns := printf "argocd-%s" .Release.Name -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ printf "guestbook" }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: v1
kind: Namespace
metadata:
  name: guestbook
  finalizers:
    - kubernetes

---